#!/usr/bin/python3

# Application for configure and maintain ALT operating system 
# (c) 2024 Andrey Cherepanov <cas@altlinux.org>

# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.                                 
                                                                    
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.                        
                                                                    
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place - Suite 330, Boston, MA  02111-1307, USA.           

from PyQt5.QtWidgets import QApplication, QWidget
from PyQt5.QtCore import QTranslator
from PyQt5 import uic
from PyQt5.QtGui import QStandardItemModel
import os
import sys
import locale

from plugins import Base

data_dir = "/usr/share/altcenter"
data_dir = "."
plugin_path = os.path.join(data_dir, "plugins")

class MainWindow(QWidget):
    """Main window"""
    def __init__(self):
        super(MainWindow, self).__init__() # Call the inherited classes __init__ method

        # Load UI from file
        uic.loadUi('mainwindow.ui', self) # Load the .ui file

        # Show window
        self.show()

# Chdir to data_dir
os.chdir(data_dir)
        
# Run application
app = QApplication(sys.argv) # Create an instance of QtWidgets.QApplication

# Load current locale translation
translator = QTranslator(app)
tr_file = "appinstall_" + locale.getlocale()[0].split( '_' )[0]
#print( "Load translation from %s.qm" % ( tr_file ) )
translator.load( tr_file )
app.installTranslator(translator)

# Initialize UI
window = MainWindow() # Create an instance of our class

# Set module list model
list_module = QStandardItemModel()
window.moduleList.setModel(list_module)

# Load plugins
for p in Base.plugins:
    inst = p()
    inst.start(list_module, window.stack)

# Start the application
sys.exit(app.exec_())
